name: ImmersiveChat
version: ${version}
api-version: 1.13
main: me.slide.immersivechat.initiators.application.ImmersiveChat
depend: [Vault, ProtocolLib, PlaceholderAPI]
softdepend: [Towny, Factions, EssentialsDiscord]
author: Slide_AM
website: https://bitbucket.org/Aust1n46/venturechat/
description: #1 Channels Chat plugin! Spigot + Bungee. Supports PlaceholderAPI + JSON formatting. Moderation GUI!
